# Generated by Django 6.0.1 on 2026-08-25 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Buyurtma beruvchi mijoz'),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name="To'liq ism"),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Salon egasi'), ('CUSTOMER', 'Mijoz')], default='OWNER', max_length=20, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='user',
            name='owner_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Egasi ismi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='salon_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Salon nomi'),
        ),
    ]
